---
title: "Untitled"
author: "Kindle Zhang qz2527"
date: "2024-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
library(mvtnorm)
library(geepack)
library(MASS)
library(gee)
```

```{r}
load("../../data_file/ICHS.RData")
load("../../data_file/MACS.RData")
load("../../data_file/Six Cities.RData")
```

```{r}
table(table(ichs$id))
```

# GEE1.0

```{r}
# Generate example data
set.seed(123)
simulate_data = function(n_subjects, n_obs_per_subject, beta, rho) {

  n = n_subjects * n_obs_per_subject
  id = rep(1:n_subjects, each = n_obs_per_subject)
  time = rep(1:n_obs_per_subject, times = n_subjects)
  
  x_1 = rnorm(n)
  x_2 = rep(rbinom(n_subjects, 1, 0.5), each = n_obs_per_subject)
  
  Sigma =
    matrix(rho, nrow = n_obs_per_subject, ncol = n_obs_per_subject)
  diag(Sigma) = 1
  
  errors =
    mvrnorm(n_subjects,
            mu = rep(0, n_obs_per_subject),
            Sigma = Sigma)
  errors = as.vector(t(errors))
  
  
  eta = beta[1] + beta[2] * x_1+ beta[3] * x_2 + errors
  y = ifelse(eta > 0, 1, 0)
  
  
  data = data.frame(id = id,
                     time = time,
                     x_1 = x_1,
                     x_2 = x_2,
                     y = y)
  return(data)
}

beta = c(-1, 3, 5) 
rho = 0.3       
data = simulate_data(n_subjects = 1000, n_obs_per_subject = 5, beta = beta, rho = rho)
```

```{r}

fit_gee1 = gee(y ~ x_1 + x_2, id = id, data = data, family = binomial,scale.fix = TRUE, corstr = "independence")
fit_gee2 = gee(y ~ x_1 + x_2, id = id, data = data, family = binomial,scale.fix = TRUE, corstr = "exchangeable")
fit_gee15 = gee(y ~ x_1 + x_2, id = id, data = data, family = binomial,scale.fix = TRUE, corstr = "ar1")



summary(fit_gee1)
summary(fit_gee2)
summary(fit_gee15)


results = data.frame(
  Model = c("GEE1", "GEE2", "GEE1.5"),
  Coef_x = c(coef(fit_gee1)[2], coef(fit_gee2)[2], coef(fit_gee15)[2]),
  SE_x = c(summary(fit_gee1)$coefficients[2, 2],
           summary(fit_gee2)$coefficients[2, 2],
           summary(fit_gee15)$coefficients[2, 2])
)

print(results)
```


```{r}
# Add manual iteration example (custom Fisher-scoring loop if needed)
# Initialize beta coefficients
beta_init = c(0, 0, 0)
max_iter = 100
tolerance = 1e-6

for (iter in 1:max_iter) {
  # Compute fitted values based on current beta
  eta = data$x1 * beta_init[2] + data$x2 * beta_init[3]
  mu = 1 / (1 + exp(-eta))  # Logit link
  
  # Compute residuals and score function
  residual = data$y - mu
  W <- diag(mu * (1 - mu))  # Variance function for logistic regression
  X <- as.matrix(cbind(1, data$x1, data$x2))  # Design matrix
  score <- t(X) %*% residual
  
  # Fisher scoring update
  hessian <- t(X) %*% W %*% X
  beta_new <- beta_init + solve(hessian) %*% score
  
  # Convergence check
  if (max(abs(beta_new - beta_init)) < tolerance) {
    break
  }
  
  beta_init <- beta_new
}

# Output final estimates
beta_new
```

